GET http://localhost:5000/users

###
GET http://localhost:5000/users/ajithvreji@gmail.com
###
DELETE http://localhost:5000/users/6292f8676d54e6d3c9ce697c
###
POST http://localhost:5000/users HTTP/1.1
content-type: application/json

{
    "name":"JaegerMaester",
    "mail":"Jmaster@gmail.com",
    "password":"since1878"
}
###

PATCH http://localhost:5000/users/62908b8be05db73217f65b73 HTTP/1.1
content-type: application/json

{
    "name":"Ajith",
    "mail":"ajithvreji@gmail.com",
    "password":"0644"
}